### ISSUE TITLE
[Original bug] No ammo weapon switching to xatrix weapons is broken

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/xatrix#40]
To see what I mean, go to src/player/weapon.c:300. Notice that xatrix added code for switching to their new guns if the player runs out of ammo for the current gun. But this is useless code, because they forgot to add return statements, so the assignment is always overridden.

This is easy enough to fix by adding the missing return statements (and making sure player has at least 2 cells for Ionripper), but do we want to? It would change gameplay from what was shipped to what was originally intended, and I'd argue it is bad to switch to the phalanx since it is an explosive weapon.

I think there are 3 options:
1. Fix both
2. Remove the phalanx entry but fix the ionripper entry
3. Remove both

Which one would you prefer?

**Comment by Yamagi** [comment]
Hi,
I agree, switching to the phalax would be a bad idea. That thing has too much splash damages, changes are high that the player will blow himself up. What about option 2, removing the phalanx and fixing the ioripper? Preferring the ioripper over the hyperblaster seems a good idea, because it's the better weapon. A little bit stronger and faster.

**Comment by BjossiAlfreds** [comment]
Yes I like option 2 the most as well. I have made a PR that makes the changes according to option 2: https://github.com/yquake2/xatrix/pull/41
