### ISSUE TITLE
Gekks´ Gibs Getting Stuck on Walls and Spinning

### ISSUE THREAD

**Issue by domyibby** [yquake2/xatrix#92]
Hello there! Big fan of your project.

I´ve recently started playing the Reckoning expansion and I´ve come across a strange looking phenomenon: when the Gekks explode, their gibs get stuck on walls and spin until they disappear.

I wonder if this is something related to the original game or if I´m doing something wrong (most likely).

I´m using the files found on the 8.20 version. I´m attaching a screenshot of the issue.

![q2_0001 (1)](https://github.com/yquake2/xatrix/assets/140016781/3bcfdee9-1d69-417a-921f-e78bf0ae073e)

Thank you so much for your support.

Regards,
domyibby

**Comment by BjossiAlfreds** [comment]
This is the original game's ancient physics system at work. Gibs and other gravity objects don't slide, so if they land on even just a slight slope they stop completely. The angular velocity keeps going because while the object stops falling, the check for ground can still fail. This could probably be fixed or improved but might introduce unexpected side-effects.

**Comment by domyibby** [comment]
Thank you for the reply!

Oh. I understand. So the footage I´ve seen of gibs behaving more ´normally´ was most likely from a source port that changed the physics of the game. Since Yamagi goes for a more authentic experience, it makes sense things like that stick around. I get it now!

Thank you!
